# absblack refind theme

banner absblack/res/banner.png

big_icon_size 256
small_icon_size 64

icons_dir absblack/res

selection_big absblack/res/selection-big.png
selection_big absblack/res/selection-small.png
