# absblack refind theme

banner absblack/res/banner.png

big_icon_size 120
small_icon_size 32

icons_dir absblack/res

selection_big absblack/res/selection_big.png
selection_big absblack/res/selection_small.png
